# Generated by Django 5.2.14 on 2026-06-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_contract_version_clause_recommendation_org_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=50, unique=True)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_contracts', models.PositiveIntegerField(default=50)),
                ('max_api_calls_per_month', models.PositiveIntegerField(default=1000)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_completed', models.JSONField(blank=True, default=list)),
                ('current_step', models.CharField(default='org_profile', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='contracts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgBillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to='contracts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='contracts.billingplan')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('contract_count', models.PositiveIntegerField(default=0)),
                ('api_call_count', models.PositiveIntegerField(default=0)),
                ('overage_users', models.BooleanField(default=False)),
                ('overage_contracts', models.BooleanField(default=False)),
                ('overage_api_calls', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='contracts.organization')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('organization', 'period_start')},
            },
        ),
    ]
