# Generated by Django 4.2.30 on 2026-06-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0043_search_telemetry_retention_cve_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='contracts.organization'),
        ),
    ]
