# Generated by Django 5.2.14 on 2026-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_backfill_workflowtemplate_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='esign_provider',
            field=models.CharField(blank=True, help_text='Outbound e-sign provider that dispatched this request', max_length=40),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='signing_url',
            field=models.CharField(blank=True, help_text='Provider signing URL returned when the request was sent', max_length=500),
        ),
    ]
