# Generated by Django 5.2.15 on 2026-06-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_signaturerequest_esign_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbillingsubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgbillingsubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orgbillingsubscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orgbillingsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orgbillingsubscription',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='free', max_length=20),
        ),
    ]
