# Generated by Django 5.2.15 on 2026-06-22 08:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_sync_mfa_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial failure'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (overlap)')], default='RUNNING', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_examined', models.PositiveIntegerField(default=0)),
                ('records_changed', models.PositiveIntegerField(default=0)),
                ('notifications_created', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_job_runs', to='contracts.organization')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='sjr_job_started_ix'), models.Index(fields=['organization', 'job_name', 'status'], name='sjr_org_job_status_ix')],
            },
        ),
    ]
