# Generated by Django 5.2.15 on 2026-06-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_scheduled_job_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(choices=[('human', 'Human'), ('service', 'Service account'), ('system', 'System'), ('scheduled_job', 'Scheduled job'), ('webhook', 'Webhook'), ('migration', 'Migration')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='hash_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = legacy self-hash (no chain); 2 = per-org hash chain.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='job_run_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='seq',
            field=models.PositiveBigIntegerField(blank=True, help_text='Per-organization monotonic sequence; NULL on legacy rows.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the canonical entry payload incl. prev_hash; see contracts.services.audit. Blank/legacy on pre-chain rows.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'seq'], name='audit_org_seq_ix'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-timestamp'], name='audit_org_ts_ix'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='audit_event_type_ix'),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.UniqueConstraint(fields=('organization', 'seq'), name='audit_org_seq_uniq'),
        ),
    ]
