# Generated by Django 5.2.15 on 2026-06-22 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0053_auditlog_append_only_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditlog',
            name='audit_org_seq_uniq',
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'seq'), name='audit_org_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True), ('seq__isnull', False)), fields=('seq',), name='audit_system_seq_uniq'),
        ),
    ]
