# Generated by Django 5.2.15 on 2026-07-07 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0061_dpa_review_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dpareviewpack',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='dpa_review_packs', to='contracts.document'),
        ),
        migrations.AddField(
            model_name='dpareviewpack',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpa_review_packs', to='contracts.matter'),
        ),
        migrations.AddField(
            model_name='dpareviewpack',
            name='related_contracts',
            field=models.ManyToManyField(blank=True, related_name='dpa_review_packs_as_related', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='dpareviewpack',
            name='review_memo_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='confidence',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('NEEDS_HUMAN_CHECK', 'Needs human check')], default='MEDIUM', max_length=25),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='conflict_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='detection_rule',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='evidence_text',
            field=models.TextField(blank=True, help_text='Verbatim snippet or concise detected excerpt that triggered this finding'),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='is_cross_document_conflict',
            field=models.BooleanField(default=False, help_text='True if this finding compares the DPA against a linked MSA/SOW rather than the DPA alone'),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='related_contract_evidence_text',
            field=models.TextField(blank=True, help_text='Verbatim snippet or concise detected excerpt from linked MSA/SOW'),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='reviewer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='source_field',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dpariskitem',
            name='source_section',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dpaplaybookposition',
            name='owner',
            field=models.CharField(blank=True, choices=[('LEGAL', 'Legal'), ('HEAD_LEGAL', 'Head of Legal'), ('DPO_SECURITY', 'DPO/Security'), ('BUSINESS', 'Business'), ('FINANCE', 'Finance'), ('DELIVERY', 'Delivery')], max_length=15),
        ),
        migrations.AlterField(
            model_name='dpariskitem',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('ACCEPTED_RISK', 'Accepted Risk'), ('FALSE_POSITIVE', 'False Positive'), ('NEEDS_BUSINESS_INPUT', 'Needs Business Input'), ('NEEDS_DPO_SECURITY_INPUT', 'Needs DPO/Security Input'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='DPAApprovalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=15)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('risk_counts_by_severity', models.JSONField(blank=True, default=dict)),
                ('unresolved_blocker_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpa_approval_history_entries', to=settings.AUTH_USER_MODEL)),
                ('review_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='contracts.dpareviewpack')),
            ],
            options={
                'verbose_name_plural': 'DPA approval history entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DPARiskItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpa_risk_item_notes', to=settings.AUTH_USER_MODEL)),
                ('risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contracts.dpariskitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
