# Generated by Django 5.2.15 on 2026-07-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0062_dpa_review_pack_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='workspace_mode',
            field=models.CharField(choices=[('law_firm_ops', 'Law firm operations'), ('in_house_clm', 'In-house CLM')], default='law_firm_ops', max_length=20),
        ),
    ]
