# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0077_seed_nda_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='workspace_mode',
            field=models.CharField(
                choices=[
                    ('law_firm_ops', 'Law firm operations'),
                    ('in_house_clm', 'In-house CLM'),
                ],
                default='in_house_clm',
                max_length=20,
            ),
        ),
    ]
