# Generated by Django 5.2.16 on 2026-08-01 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0115_exception_correlation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIngestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('QUARANTINED', 'Quarantined'), ('SCANNING', 'Scanning'), ('CLEAN', 'Clean'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], default='RECEIVED', max_length=20)),
                ('verdict', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CLEAN', 'Clean'), ('MALICIOUS', 'Malicious'), ('UNSCANNABLE', 'Unscannable'), ('ERROR', 'Error')], default='UNKNOWN', max_length=20)),
                ('quarantine_object_key', models.CharField(blank=True, default='', max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size', models.PositiveBigIntegerField()),
                ('detected_media_type', models.CharField(max_length=100)),
                ('scanner_provider', models.CharField(blank=True, default='', max_length=100)),
                ('scanner_signature_version', models.CharField(blank=True, default='', max_length=120)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_ingestion_attempts', to='contracts.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_ingestion_attempts', to='contracts.contract')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_ingestion_attempts', to='contracts.matter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_ingestion_attempts', to='contracts.organization')),
                ('released_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_attempts', to='contracts.document')),
                ('released_document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_attempts', to='contracts.documentversion')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_ingestion_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'received_at'], name='docing_org_status_ix'), models.Index(fields=['organization', 'file_hash'], name='docing_org_hash_ix')],
            },
        ),
    ]
