# Generated by Django 5.2.16 on 2026-08-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0116_canonical_workflow_nda_runtime"),
        ("contracts", "0117_userprofile_totp"),
    ]

    operations = []
